### PR TITLE
Handling KaiConnected, saving capabilities to memory

### LINKED ISSUE #8: KaiConnected Event not handled
The library should be able to handle the `kaiConnected` event when a new Kai gets connected

### LINKED ISSUE #9: Remove exception to silently ignore if not authenticated
This might be called before authentication. The `Connect()` function will handle setting the capabilities after authentication. So this should ideally silently ignore it rather than throwing an exception.
https://github.com/vicara-hq/kai-dotnet/blob/0c2c1c28519c00c814da342d57bd5dbfd76fbf8f/Kai.BaseModule/KaiSDK.cs#L101

### LINKED ISSUE #10: Save KaiCapabilities for SetCapabilities to library memory
- Save capabilities to kai.Capabilities, before checking if Authenticated https://github.com/vicara-hq/kai-dotnet/blob/0c2c1c28519c00c814da342d57bd5dbfd76fbf8f/Kai.BaseModule/KaiSDK.cs#L98
- return if not authenticated
- call SetCapabilities function again after Authentication success response received only for  DefaultKai/ DefaultLeftKai/ DefaultRightKai 
- only DefaultKai/ DefaultLeftKai/ DefaultRightKai  capabilities can be set immediately after Authentication success response, and before receiving list of connected Kais
- for other Kais, call SetCapabilities after list of connected Kais received from the sdk.
- Add logic before the if check for Authentication https://github.com/vicara-hq/kai-dotnet/blob/0c2c1c28519c00c814da342d57bd5dbfd76fbf8f/Kai.BaseModule/KaiSDK.cs#L100

### PR DESCRIPTION
**Pull request by r4reejh**
fixes #9 , partially-fixes #10 , fixes #8

### CODE REVIEW

File: Kai.BaseModule/KaiSDK.cs [hunk 1]
```diff
@@ -7,7 +7,7 @@ namespace Kai.Module
 {
 	public static partial class KaiSDK
 	{
-		private static Kai[] connectedKais = new Kai[8];
+		public static Kai[] connectedKais { get; private set; } = new Kai[8];
```
Comment (rakshith-ravi) [inline Kai.BaseModule/KaiSDK.cs]: Why is this public?

File: Kai.BaseModule/KaiSDK.cs [hunk 2]
```diff
@@ -561,5 +575,24 @@ private static void DecodeConnectedKais(JObject input)
...
+				handEnum = Hand.Left;
+			
+			connectedKais[kaiID] = new Kai
+			{
+				KaiID = kaiID,
+				Hand = handEnum
+			};
+
+			if (defaultKai == true)
+				DefaultKai = connectedKais[kaiID];
```
Comment (rakshith-ravi) [inline Kai.BaseModule/KaiSDK.cs]: This line would delete the `Default` reference which will end up losing all the events that the user has subscribed to. The `Default` object has to remain constant and cannot change.

File: Kai.BaseModule/KaiSDK.cs [hunk 3]
```diff
@@ -528,11 +542,11 @@ private static void DecodeConnectedKais(JObject input)
 			{
 				var kai = token.ToObject<JObject>();
 				var kaiID = kai[Constants.KaiId].ToObject<int>();
-				var hand = kai[Constants.Hand].ToObject<string>();
+				var hand = kai[Constants.Hand]?.ToObject<string>();
```
Comment (rakshith-ravi) [inline Kai.BaseModule/KaiSDK.cs]: The SDK is supposed to send the hand of the Kai while connection. I don't think we should keep this as an optional parameter.

File: Kai.BaseModule/KaiSDK.cs [hunk 4]
```diff
@@ -517,7 +526,12 @@ void FireMagnetometerEvent(MagnetometerEventArgs args)
 
 		private static void DecodeAuthentication(JObject input)
 		{
-			Authenticated = input[Constants.Authenticated].ToObject<bool>();
+			//Authenticated = input[Constants.Authenticated].ToObject<bool>();
```
Comment (rakshith-ravi) [inline Kai.BaseModule/KaiSDK.cs]: Please revert back to this. The SDK will be updated accordingly. Don't want these temporary work-arounds getting into the mainstream code.

File: Kai.BaseModule/KaiSDK.cs [hunk 5]
```diff
@@ -44,7 +44,7 @@ public static partial class KaiSDK
 		/// <summary>
 		/// Contains the value of the default Kai that is connected to the SDK
 		/// </summary>
-		public static Kai DefaultKai { get; } = new Kai();
+		public static Kai DefaultKai { get; private set; } = new Kai();
```
Comment (rakshith-ravi) [inline Kai.BaseModule/KaiSDK.cs]: Since the `DefaultKai` is supposed to be a constant and should, ideally, never change, I'd suggest we have just a public getter and no setter
```suggestion
		public static Kai DefaultKai { get; } = new Kai();
```

**Comment by rakshith-ravi** [comment]
Also, I was thinking, since we're decoding a Kai object quite frequently, perhaps that can be abstracted away into a private function to avoid rewriting code again and again

File: Kai.BaseModule/KaiSDK.cs (hunk 3 above)
Comment (r4reejh) [reply Kai.BaseModule/KaiSDK.cs]: Alright

File: Kai.BaseModule/KaiSDK.cs (hunk 2 above)
Comment (r4reejh) [reply Kai.BaseModule/KaiSDK.cs]: Ok, so just set Default.KaiId and Default.Hand

Comment (rakshith-ravi) [reply Kai.BaseModule/KaiSDK.cs]: Yes, exactly

File: Kai.BaseModule/KaiSDK.cs [hunk 6]
```diff
@@ -89,21 +89,35 @@ public static void Connect()
 			// Test compatibility
 			// Send capabilities
 		}
-		
+
 		/// <summary>
 		/// Sets the Kai's capabilities and subscribes to that data
```
Comment (rakshith-ravi) [inline Kai.BaseModule/KaiSDK.cs]: Wrong documentation xD
I'll let this go for now, but let's fix it up.
